### ISSUE TITLE
Not working in Safari and iOS devices

### ISSUE THREAD

**Issue by shreyshahh** [killroywashere/ng-audio-recorder#1]
Audio recorder does not work in safari and also not working in any other browser in iOS devices. 
It says **cannot find variable mediaRecorder**
  Any solution for this?

My code,

```
startRecording() { // this will be called on a button click
   
      this.audioRecorderService.startRecording();
  
      setTimeout(() => {
        this.stopRecording();
      }, 5000);
  }

  stopRecording() {
    this.audioRecorderService.stopRecording(0).then((output: any) => {
      // do post output steps
      this.audioFile = this.dSanitizer.bypassSecurityTrustResourceUrl(output);
      
    }).catch(errrorCase => {
      // Handle Error
      console.log(errrorCase);
    });
  }
```

in HTML,
```
<audio controls type="audio/mp4" [src]="audioFile">
                    </audio>
```

**Comment by orr3** [comment]
Not sure if this applies to your problem. My code was working in Chrome on Mac OS, but in iOS Safari I got this error message:

`TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.enumerateDevices')`

It turned out that iOS demands the connection to be over HTTPS for the microphone access to be available (probably the same applies for camera access). So implementing my localhost server to serve over HTTPS and suddenly Safari asked for permission and started recording.
